
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :log => {
        :box_name => "centos/7",
        :ip_addr => '192.168.0.1'
	},
  :web => {
        :box_name => "centos/7",
        :ip_addr => '192.168.0.2'
	}
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s
	  
 	  config.vm.provider "virtualbox" do |v|
            v.memory = 256
          end

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]
	  box.vm.provider :virtualbox do |vb|
	      vb.customize ["modifyvm", :id, "--memory", "256"]
	  end
          box.vm.provision "shell", inline: <<-SHELL
	      mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
  	  SHELL
	  case boxname.to_s
          when "web"
	    box.vm.provision :ansible do |ansible|
             ansible.limit = "all"
             ansible.playbook = "ansible/web.yml"
           end
         when "log"
	   box.vm.provision :ansible do |ansible|
             ansible.limit = "all"
             ansible.playbook = "ansible/log.yml"
           end
         end
      end
  end
end
