
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :monitoring => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.2'
	}
}


Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s
	  
 	  config.vm.provider "virtualbox" do |v|
            v.memory = 256
          end

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]
	  box.vm.provider :virtualbox do |vb|
	      vb.customize ["modifyvm", :id, "--memory", "256"]
	  end
          box.vm.provision "shell", inline: <<-SHELL
	      mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
              curl -Ssl https://get.docker.com | sh
              systemctl start docker
	      docker run -d -p 9100:9100 -v /proc:/host/proc:ro -v /sys:/host/sys:ro --name exporter prom/node-exporter
	      docker run -d -p 9090:9090 -v /vagrant/prometheus.yml:/etc/prometheus/prometheus.yml --link exporter --name prometheus prom/prometheus
	      docker run -d -p 3000:3000 --link prometheus --name grafana grafana/grafana
	      # а потом ручками импортим дашборд 6287
  	  SHELL
	  #case boxname.to_s
          #when "monitoring"
	  #  box.vm.provision :ansible do |ansible|
          #   ansible.limit = "all"
          #   ansible.playbook = "ansible/monitoring.yml"
          # end 
        # end
      end
  end
end
