# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
 :s1 => {
	:box_name => "centos/7",
	:net => [
		  {adapter: 2, auto_config: false, virtualbox__intnet: 'vlan1'},
		  {adapter: 3, auto_config: false, virtualbox__intnet: 'vlan2'},
		  {adapter: 4, auto_config: false, virtualbox__intnet: "a1"}
		]
},  
 :s2 => {
	:box_name => "centos/7",
	:net => [
		  {adapter: 2, auto_config: false, virtualbox__intnet: 'vlan1'},
		  {adapter: 3, auto_config: false, virtualbox__intnet: 'vlan3'},
		  {adapter: 4, auto_config: false, virtualbox__intnet: "a2"}

		]
},
:s3 => {
	:box_name => "centos/7",
	:net => [
		  {adapter: 2, auto_config: false, virtualbox__intnet: 'vlan2'},
		  {adapter: 3, auto_config: false, virtualbox__intnet: 'vlan3'},
		  {adapter: 4, auto_config: false, virtualbox__intnet: "a3"}

		]
},

}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s
	

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
		# срипач не нужен
		setenforce 0
		systemctl stop firewalld
		systemctl disable firewalld
		systemctl mask firewalld
		echo net.ipv4.conf.all.forwarding=1  >> /etc/sysctl.conf
                echo net.ipv4.ip_forward=1 >> /etc/sysctl.conf
                echo net.ipv4.conf.all.rp_filter=0 >> /etc/sysctl.conf
		sysctl -p /etc/sysctl.conf
		yum -y install quagga
		echo -e 'zebra=yes\nbgpd=no\nospfd=yes\nospf6d=no\nripd=no\nripngd=no' > /etc/quagga/daemons
        SHELL
        
        case boxname.to_s
	when "s1"
	 box.vm.provision "shell", run: "always", inline: <<-SHELL
		echo -e "NM_CONTROLLED=no\nBOOTPROTO=none\nONBOOT=yes\nIPADDR=10.1.0.1\nNETMASK=255.255.255.0\nDEVICE=eth3\nPEERDNS=no" > /etc/sysconfig/network-scripts/ifcfg-eth3
		echo -e "DEVICE=eth1.1\nVLAN=yes\nBOOTPROTO=static\nONBOOT=yes\nTYPE=Ethernet\nIPADDR=192.168.16.1\nPREFIX=30\nNM_CONTROLLED=no" > /etc/sysconfig/network-scripts/ifcfg-vlan1
		echo -e "DEVICE=eth2.2\nVLAN=yes\nBOOTPROTO=static\nONBOOT=yes\nTYPE=Ethernet\nIPADDR=192.168.17.1\nPREFIX=30\nNM_CONTROLLED=no" > /etc/sysconfig/network-scripts/ifcfg-vlan2
		echo -e "hostname s1\ninterface eth1\nip address 192.168.16.1/30\ninterface eth2\nip address 192.168.17.1/30\ninterface eth3\nip address 10.1.0.1/24\nlog file /var/log/quagga/zebra.log" > /etc/quagga/zebra.conf
		echo -e "hostname s1\nrouter ospf\n	ospf router-id 192.168.16.1\n	network 192.168.16.0/30 area 0\n	network 192.168.17.0/30 area 0\n	network 10.1.0.0/24 area 1\nredistribute connected\nlog file /var/log/quagg/ospfd.log" > /etc/quagga/ospfd.conf
		systemctl restart network
		systemctl start zebra
		systemctl start ospfd
		SHELL
	when "s2"
	 box.vm.provision "shell", run: "always", inline: <<-SHELL
		echo -e "NM_CONTROLLED=no\nBOOTPROTO=none\nONBOOT=yes\nIPADDR=10.2.0.1\nNETMASK=255.255.255.0\nDEVICE=eth3\nPEERDNS=no" > /etc/sysconfig/network-scripts/ifcfg-eth3
		echo -e "DEVICE=eth1.1\nVLAN=yes\nBOOTPROTO=static\nONBOOT=yes\nTYPE=Ethernet\nIPADDR=192.168.16.2\nPREFIX=30\nNM_CONTROLLED=no" > /etc/sysconfig/network-scripts/ifcfg-vlan1
		echo -e "DEVICE=eth2.3\nVLAN=yes\nBOOTPROTO=static\nONBOOT=yes\nTYPE=Ethernet\nIPADDR=192.168.18.1\nPREFIX=30\nNM_CONTROLLED=no" > /etc/sysconfig/network-scripts/ifcfg-vlan3
		echo -e "hostname s2\ninterface eth1\nip address 192.168.16.2/30\ninterface eth2\nip address 192.168.18.1/30\ninterface eth3\nip address 10.2.0.1/24\nlog file /var/log/quagga/zebra.log" > /etc/quagga/zebra.conf
		echo -e "hostname s2\nrouter ospf\n	ospf router-id 192.168.16.2\n	network 192.168.16.0/30 area 0\n	network 192.168.18.0/30 area 0\n	network 10.2.0.0/24 area 1\nredistribute connected\nlog file /var/log/quagg/ospfd.log" > /etc/quagga/ospfd.conf
		systemctl restart network
		systemctl start zebra
		systemctl start ospfd
		SHELL
	when "s3"
	 box.vm.provision "shell", run: "always", inline: <<-SHELL
		echo -e "NM_CONTROLLED=no\nBOOTPROTO=none\nONBOOT=yes\nIPADDR=10.3.0.1\nNETMASK=255.255.255.0\nDEVICE=eth3\nPEERDNS=no" > /etc/sysconfig/network-scripts/ifcfg-eth3
		echo -e "DEVICE=eth1.2\nVLAN=yes\nBOOTPROTO=static\nONBOOT=yes\nTYPE=Ethernet\nIPADDR=192.168.17.2\nPREFIX=30\nNM_CONTROLLED=no" > /etc/sysconfig/network-scripts/ifcfg-vlan2
		echo -e "DEVICE=eth2.3\nVLAN=yes\nBOOTPROTO=static\nONBOOT=yes\nTYPE=Ethernet\nIPADDR=192.168.18.2\nPREFIX=30\nNM_CONTROLLED=no" > /etc/sysconfig/network-scripts/ifcfg-vlan3
		echo -e "hostname s3\ninterface eth1\nip address 192.168.17.2/30\ninterface eth2\nip address 192.168.18.2/30\ninterface eth3\nip address 10.3.0.1/24\nlog file /var/log/quagga/zebra.log" > /etc/quagga/zebra.conf
		echo -e "hostname s3\nrouter ospf\n	ospf router-id 192.168.17.2\n	network 192.168.17.0/30 area 0\n	network 192.168.18.0/30 area 0\n	network 10.3.0.0/24 area 1\nredistribute connected\nlog file /var/log/quagg/ospfd.log" > /etc/quagga/ospfd.conf
		systemctl restart network
		systemctl start zebra
		systemctl start ospfd
		SHELL

        end
end
end
end
