- name: enable all forwarding
  sysctl:
    name: net.ipv4.conf.all.forwarding
    value: 1
    state: present
    reload: yes
- name: enable forward
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    reload: yes
- name: copy knock script
  copy:
    src: knock.sh
    dest: /vagrant/knock.sh
    mode: 0775
    owner: vagrant
    group: vagrant
- name: fuck firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no
    masked: yes
- name: install nmap
  yum:
    name: nmap
    state: latest
- name: edit eth0 config
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0 
    line: DEFROUTE=no
- name: add gateway to eth1 config
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth1
    line: GATEWAY=192.168.255.1
- name: restart network
  systemd:
    name: network
    state: restarted
- name: add route1
  shell: ip route add 192.168.2.0/24 via 192.168.100.2
- name: add route2
  shell: ip route add 192.168.1.0/24 via 192.168.110.2
