
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :master => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.2'
	},
  :slave => {
	:box_name => "centos/7",
        :ip_addr => '192.168.11.3'
	}
}


Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s
	  
 	  config.vm.provider "virtualbox" do |v|
            v.memory = 512
          end

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset
          box.vm.network "private_network", ip: boxconfig[:ip_addr]
	  box.vm.provider :virtualbox do |vb|
	      vb.customize ["modifyvm", :id, "--memory", "512"]
	  end
          box.vm.provision "shell", inline: <<-SHELL
	      mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
  	  SHELL
	  case boxname.to_s
          when "master"
	    box.vm.provision :ansible do |ansible|
	     #ansible.verbose = "vvv"
             ansible.limit = "all"
             ansible.playbook = "ansible/master.yml"
           end 
          when "slave"
            box.vm.provision :ansible do |ansible|
	     #ansible.verbose = "vvv"
             ansible.limit = "all"
             ansible.playbook = "ansible/slave.yml"
	   end
         end
      end
  end
end
